# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8248a3791f57fbd2a554f005db760172c5e02332a331cdfec5330386e25e4dd1af5787b4183937d92bf99dfb2807da0c929894dd0f730eee05047b3bc685c871

test:
  secret_key_base: 7e7710e297308085ec45e358f82e2b9149fb29736fa0125552aedde2ce5739f162613aa2ab882ab466cbbaa9de288c9b84fdd8d56b1a401b48b5cadb62bf6d4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
